// Builds the browser code with esbuild:
//   public/app/page.js   the standalone page (page.mjs: the screens plus the formula engine, Yjs and SSF)
//   screens.mjs          the suite's screen part (sheets.mjs with sheets.css carried inside, scoped to .sheets-root)
// --check fails if either is out of date with its sources.
import fs from 'node:fs';
import { build } from 'esbuild';
import { scopeCss } from './scope-css.mjs';

const common = { bundle: true, format: 'esm', platform: 'browser', target: 'es2022', minify: true, legalComments: 'none', write: false, logLevel: 'error', define: { 'process.env.WOS_ACCOUNT_URL': 'undefined' } };
const page = await build({ ...common, entryPoints: ['public/app/page.mjs'] });
const css = scopeCss(fs.readFileSync('public/app/sheets.css', 'utf8'), '.sheets-root');
const screens = await build({ ...common, entryPoints: ['public/app/sheets.mjs'], banner: { js: `// GENERATED by scripts/build-screens.mjs from public/app/*.mjs and sheets.css. Do not edit by hand.\nconst SHEETS_CSS = ${JSON.stringify(css)};\nif (typeof document !== 'undefined' && !document.getElementById('sheets-css')) { const s = document.createElement('style'); s.id = 'sheets-css'; s.textContent = SHEETS_CSS; document.head.appendChild(s); }` } });
const out = { 'public/app/page.js': page.outputFiles[0].text, 'screens.mjs': screens.outputFiles[0].text };
if (process.argv.includes('--check')) {
  for (const [f, t] of Object.entries(out)) if (!fs.existsSync(f) || fs.readFileSync(f, 'utf8') !== t) { console.error(`${f} is out of date: run npm run build`); process.exit(1); }
  console.log('built files are current');
} else {
  for (const [f, t] of Object.entries(out)) fs.writeFileSync(f, t);
  console.log(`wrote public/app/page.js (${Math.round(out['public/app/page.js'].length / 1024)} KB) and screens.mjs (${Math.round(out['screens.mjs'].length / 1024)} KB)`);
}
